remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Nestle 1904 GNT (LowFat Trees)
description: TextFabric dataset for Greek New Testament based upon Nestle 1904 (LowFat tree dataset)
show_downloads: false
