remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap

title: Nestle 1904 GNT (Low Fat Trees)
description: Text-Fabric dataset for Greek New Testament based upon Nestle 1904 (Low Fat tree dataset)
show_downloads: false
